// Copyright 2021 Ben

export default `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque non imperdiet lorem, vel finibus ligula. Aenean dui augue, consequat a nisi et, condimentum maximus massa. In commodo lacus lorem, id iaculis quam ornare vitae. Integer mauris odio, tempus eget nulla id, interdum porta arcu. Nullam in sagittis sapien. Suspendisse sit amet dignissim mi, non euismod velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

Praesent feugiat enim eget laoreet ullamcorper. Praesent tincidunt eleifend orci, malesuada lobortis elit imperdiet et. Sed at lorem lectus. Vivamus aliquet sed purus ut volutpat. In sit amet laoreet urna. Donec imperdiet ultrices dignissim. Praesent a vehicula dolor, a dignissim lacus. Aliquam aliquam ullamcorper semper. Etiam at odio finibus, molestie quam quis, fermentum metus.

Nam placerat nisl et tincidunt porttitor. Proin fringilla laoreet egestas. Vestibulum mi massa, mollis ac mi at, gravida feugiat elit. Aliquam interdum sodales leo et maximus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vitae cursus risus, nec aliquam nunc. Aliquam fringilla semper quam at ultrices. Sed eget euismod nulla, a maximus odio. Pellentesque rutrum purus congue, placerat mauris in, tempus magna.

Integer iaculis nisi nulla, ac consectetur sem euismod ut. Phasellus metus mauris, semper ut ex id, convallis dapibus arcu. Donec quis sodales erat. Proin facilisis ex purus, quis consectetur odio maximus non. Donec tristique volutpat quam, quis mollis massa blandit quis. Aliquam nec tellus dui. Mauris vestibulum nibh vel lacus gravida, in laoreet elit volutpat. Vestibulum libero arcu, gravida vel accumsan ut, suscipit vitae nulla. Etiam sodales hendrerit enim ut scelerisque. Nullam a massa non nulla auctor varius. Curabitur mattis arcu sollicitudin, consequat metus non, ornare tortor. Maecenas vestibulum urna quis dignissim commodo. Morbi efficitur, nulla a imperdiet laoreet, elit nisi pharetra lacus, eget tristique mi mi ut justo.

In iaculis justo orci, sit amet ultrices nunc pellentesque eu. Sed at lacinia tortor. Nullam porttitor a orci ut gravida. Etiam fermentum turpis quis felis tempor gravida. Suspendisse at turpis purus. Ut faucibus, orci in porttitor ornare, purus massa bibendum nisi, vel efficitur eros dui sit amet ligula. Integer lacinia convallis commodo. Ut laoreet dignissim ante ac scelerisque. Nulla eu laoreet eros. Morbi vehicula, nisi in tincidunt pulvinar, orci sem commodo orci, finibus mollis leo eros vel nulla. Nam vulputate arcu dolor, sit amet sagittis ligula pretium eget. Mauris volutpat sed nibh id aliquam.

`


const textArr = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ut egestas mi. Nam finibus justo id est egestas ornare. Cras scelerisque nulla vitae nisi ultrices, id molestie erat lobortis. Proin consectetur pretium massa, eget cursus lectus egestas sed. Curabitur tristique faucibus orci at condimentum. Fusce neque metus, fermentum nec nisl vitae, faucibus rutrum diam. Aliquam erat volutpat.",
"Integer malesuada mauris sed ligula suscipit, id egestas velit laoreet. Phasellus nec imperdiet ex, elementum pellentesque erat. Aliquam ut libero at orci aliquet mollis a in sem. Cras sagittis, leo ac luctus commodo, felis purus convallis massa, sed pharetra nunc erat at est. Duis posuere, ligula in lobortis scelerisque, nisi arcu imperdiet ligula, sed vulputate nisl massa sit amet nibh. In hac habitasse platea dictumst. Integer semper velit sed dolor malesuada, ac accumsan eros tempus. Ut tincidunt arcu id odio ullamcorper venenatis.",
"Quisque mollis pharetra neque. Maecenas mauris ligula, iaculis vitae eros iaculis, finibus pellentesque lectus. Nullam feugiat, lectus vel gravida consequat, erat sem vestibulum libero, eu malesuada elit ligula nec urna. Nunc posuere ac libero in varius. In hendrerit ac nisi nec consectetur. Sed egestas, elit a dapibus laoreet, augue velit consequat nisi, quis tincidunt diam urna ut mi. Suspendisse potenti. Maecenas eleifend dapibus ante eget scelerisque. Sed bibendum, turpis ac molestie volutpat, quam tortor fermentum leo, eget mollis nisi nisl non erat. Vestibulum sit amet dapibus augue, et cursus arcu. Aenean sagittis enim erat, ut scelerisque erat eleifend finibus. Duis placerat tortor tellus, at semper augue vulputate sed.",
"Curabitur sodales arcu erat, vel dapibus nisl bibendum nec. Proin mollis metus nec mauris faucibus iaculis. Nam quis sagittis sem. Ut ultricies leo ac odio gravida pulvinar. Aliquam ex sapien, auctor et suscipit non, viverra eu metus. Duis a arcu erat. Aenean mollis, eros a consequat elementum, nunc massa consectetur urna, ut tempus turpis augue at enim. Praesent tempus felis et mi tempus, id vestibulum turpis viverra. Vivamus ac tortor ut ipsum rutrum gravida in vel urna. Curabitur hendrerit tempor dolor, ut ornare lectus hendrerit eget. Phasellus et ipsum justo. Cras fringilla varius lobortis. Duis a fermentum urna. Sed pellentesque orci nisi, non feugiat nisi fermentum sed. Vivamus lectus nisi, bibendum quis cursus id, rhoncus sit amet elit.",
"Sed hendrerit erat ut quam iaculis, a tempus neque maximus. Etiam odio leo, suscipit ac dui eu, lobortis suscipit orci. Praesent finibus mollis arcu sed porta. Mauris sem tortor, efficitur at ultricies id, dictum nec quam. Nullam quis eros vel turpis aliquam dictum. Vivamus dui augue, molestie sed tortor a, pellentesque vulputate turpis. Praesent eget aliquet diam. Suspendisse egestas non nisi eget sollicitudin. Fusce tincidunt consectetur iaculis. Donec in urna enim. Ut efficitur lacus mauris, id lobortis tortor mattis et. Donec commodo ante non nisl scelerisque, eu molestie ligula tincidunt. Suspendisse risus leo, ultrices at blandit et, pharetra quis mauris. Proin suscipit urna nibh, dictum semper nibh efficitur et. Donec iaculis dignissim turpis, sit amet placerat dui malesuada a. In ut euismod erat."];
